### ISSUE TITLE
Why does this contract have a reentrancy bug?

### ISSUE THREAD

**Issue by leonardoalt** [melonproject/oyente#140]
Hi,
I would assume this contract is safe with respect to reentrancy, but Oyente says otherwise. Why is that?
```
pragma solidity ^0.4.11;

contract T {
    uint a;

  function t() {
        if (a > 0) {
            uint b = a;
            a = 0;
            msg.sender.transfer(b);
        }
  }
  
}
```

**Comment by luongnt95** [comment]
@leonardoalt I fixed the issue and here is my [https://github.com/melonproject/oyente/pull/141/files](PR)

**Comment by leonardoalt** [comment]
If the storage var is a ``map`` instead of ``uint``, the bug is back..
```
contract T {
    mapping (address => uint) map;
    function f() {
        if(map[msg.sender] > 0) {
            uint b = map[msg.sender];
            map[msg.sender] = 0;
            msg.sender.transfer(b);
        }
    }
}
```

**Comment by luongnt95** [comment]
Thanks @leonardoalt  I'm fixing this bug. I will get back to you when I've done

**Comment by leonardoalt** [comment]
Ok @luongnt95, thanks!

**Comment by loiluu** [comment]
@luongnt95 this is different from the bug you are fixing. It should not be a bug with our current implementation. Please double check and see where it goes wrong.

**Comment by luongnt95** [comment]
@leonardoalt The bug has been fixed. Here is my [commit](https://github.com/melonproject/oyente/commit/862d0dcff472ff272bf16df61b8f3f0ddf77cd61)
